### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by chr7stos** [rugging24/python-testcompose#12]
Cabron, I was getting familiarised with the README and the project, and I wanted to open a PR that updates some minor things in the README.

I do not have access for that, so I write it here in case you want to integrate it in the README.

---
**Testcompose** provides an easy way of using docker containers for functional and integration testing. It allows for combination of more than one containers and allows for interactions with these containers from your test code without having to write extra scripts for such interactions. I.e providing a docker compose kind of functionality with the extra benefit of being able to fully control the containers from test codes.

This is inspired by the  [testcontainers-python](https://testcontainers-python.readthedocs.io/en/latest/index.html#) project and goes further to add a few additional functionalities to improve software integration testing while allowing the engineer to control every aspect of the test.

---

**Comment by rugging24** [comment]
Fixed with (commit)[https://github.com/rugging24/python-testcompose/commit/347a4f38bc2ff9d761fe833867c2638bfeb92aee]
